name: Tests

on:
  push:
    branches:
    - dev
    - main

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    steps:
    - name: Say hello world
      shell: bash
      run: |
        echo "Welcome to the Github Actions workshop !"
  unit-tests:
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker
    steps:
    - uses: actions/checkout@v2
    - name: Run unit-tests
      run: make tests_run > output.txt
    - name: Run coverage
      run: make coverage
    - uses: actions/upload-artifact@v2 > output.txt
      with:
        name: output
        path: output.txt